// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqtujstdzrnmruccaibq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxdHVqc3RkenJubXJ1Y2NhaWJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTg3MjksImV4cCI6MjA2MzczNDcyOX0.0LyCxYfa14cNL7E1NeyomflsB8FOscT0gB5s3O30fMg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});